Repository LikeLion-3/donationProject, pull requests merged in 2023-11, with the labels that each got.

#3 fix: #2 수정했던 코드 누락 추가
  src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  src/main/java/com/myapp/warmwave/domain/chat/entity/ChatMessage.java
  src/main/java/com/myapp/warmwave/domain/chat/entity/ChatRoom.java
  src/main/java/com/myapp/warmwave/domain/favorite_inst/entity/FavoriteInst.java
  src/main/java/com/myapp/warmwave/domain/image/entity/Image.java
  src/main/java/com/myapp/warmwave/domain/temperture/entity/Temperature.java
  src/main/java/com/myapp/warmwave/domain/user/entity/Individual.java
Labels: BE, FIX

#8 [TEST]기관 회원 관련 레포지토리 테스트코드 작성
  src/main/java/com/myapp/warmwave/common/BaseEntity.java
  src/main/java/com/myapp/warmwave/config/JpaConfig.java
  src/main/java/com/myapp/warmwave/domain/address/entity/Address.java
  src/main/java/com/myapp/warmwave/domain/address/repository/AddressRepository.java
  src/main/java/com/myapp/warmwave/domain/image/entity/Image.java
  src/main/java/com/myapp/warmwave/domain/image/repository/ImageRepository.java
  src/main/java/com/myapp/warmwave/domain/temperture/repository/TemperatureRepository.java
  src/main/java/com/myapp/warmwave/domain/user/entity/Individual.java
  src/main/java/com/myapp/warmwave/domain/user/entity/Institution.java
  src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  src/main/java/com/myapp/warmwave/domain/user/repository/IndividualRepository.java
  src/main/java/com/myapp/warmwave/domain/user/repository/InstitutionRepository.java
  src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  src/test/java/com/myapp/warmwave/user/repository/UserRepositoryTest.java
Labels: BE, TEST

#13 [FEAT] 기관 회원 CRUD
  src/main/java/com/myapp/warmwave/config/PasswordEncoderConfig.java
  src/main/java/com/myapp/warmwave/domain/address/repository/AddressRepository.java
  src/main/java/com/myapp/warmwave/domain/address/service/AddressService.java
  src/main/java/com/myapp/warmwave/domain/temperture/controller/TemperatureController.java
  src/main/java/com/myapp/warmwave/domain/temperture/dto/TemperatureDto.java
  src/main/java/com/myapp/warmwave/domain/temperture/entity/Temperature.java
  src/main/java/com/myapp/warmwave/domain/temperture/repository/TemperatureRepository.java
  src/main/java/com/myapp/warmwave/domain/temperture/service/TemperatureService.java
  src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  src/main/java/com/myapp/warmwave/domain/user/dto/RequestInstitutionJoinDto.java
  src/main/java/com/myapp/warmwave/domain/user/dto/RequestInstitutionUpdateDto.java
  src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserDto.java
  src/main/java/com/myapp/warmwave/domain/user/dto/UserDto.java
  src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  src/test/java/com/myapp/warmwave/user/repository/UserRepositoryTest.java
  src/test/java/com/myapp/warmwave/user/service/UserServiceTest.java
Labels: BE, FEATURE, FIX, TEST

#19 [Feat] JWT configuration
  build.gradle
  src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  src/main/java/com/myapp/warmwave/common/security/SecurityConfig.java
  src/main/java/com/myapp/warmwave/common/util/Utils.java
  src/main/resources/application-secret.yml.default
Labels: BE, FEATURE

#21 [FIX] 서비스 로직 수정
  src/main/java/com/myapp/warmwave/domain/address/service/AddressService.java
  src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
Labels: BE, FIX

#25 [Feat] 채팅 관련 백엔드 서비스 코드 작성
  BE/build.gradle
  BE/src/main/java/com/myapp/warmwave/domain/chat/config/WebSocketConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatMessageController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatRoomController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatMessageDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/entity/ChatMessage.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/entity/ChatRoom.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/repository/ChatRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/repository/ChatRoomRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatMessageService.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatRoomService.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatService.java
Labels: BE, FEATURE

#27 [FEAT] 개인회원 CRU
  BE/src/main/java/com/myapp/warmwave/domain/address/service/AddressService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestIndividualJoinDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestIndividualUpdateDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Individual.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/java/com/myapp/warmwave/domain/user/repository/IndividualRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
Labels: BE, FEATURE

#30 [DESIGN] 메인페이지 디자인 수정
  FE/src/assets/css/templatemo-woox-travel.css
  FE/src/assets/images/cta-bg.jpg
Labels: FE, DESIGN

#34 [FEAT] 회원가입 시 이메일인증 로직 구현
  BE/build.gradle
  BE/src/main/java/com/myapp/warmwave/domain/email/dto/RequestEmailAuthDto.java
  BE/src/main/java/com/myapp/warmwave/domain/email/entity/EmailAuth.java
  BE/src/main/java/com/myapp/warmwave/domain/email/repository/EmailAuthRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/email/service/EmailService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestInstitutionJoinDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestUserLoginDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserJoinDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserLoginDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  BE/src/main/resources/application.yml
Labels: BE, FEATURE, FIX

#36 [FIX] 게시글 페이지 조회 API 결과에 따른 페이지 수정
  BE/src/main/java/com/myapp/warmwave/common/security/CorsConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticleResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
Labels: BE, FE, FIX, DESIGN
