Repository LikeLion-3/donationProject, pull requests merged in 2023-12, with the labels that each got.

#38 Feature/#37
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/CustomOAuth2User.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/KakaoOAuth2UserInfo.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2LoginFailureHandler.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2UserInfo.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuthAttributes.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/SocialType.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/service/CustomOAuth2UserService.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/service/CustomUserDetailsService.java
  BE/src/main/java/com/myapp/warmwave/config/security/CorsConfig.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  BE/src/main/resources/application-secret.yml.default
  BE/src/main/resources/application.yml
Labels: BE, FEATURE, REFACTOR

#40 [FEAT] 회원 로그인 구현
  BE/build.gradle
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
Labels: BE, FEATURE

#43 [FIX] 자잘한 수정 작업 진행
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuthAttributes.java
  BE/src/main/resources/application.yml
Labels: BE

#49 [REFACTOR] Security & JWT & OAuth configuration
  .gitignore
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/test/java/com/myapp/warmwave/jwt/JwtTests.java
Labels: BE, FEATURE, REFACTOR, TEST

#53 [FIX] 메인페이지 지도 연동
  BE/src/main/java/com/myapp/warmwave/common/main/dto/MainInstDto.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  FE/src/component/main/home/NewArticle.js
  FE/src/component/main/home/articles/Top5Articles.js
  FE/src/component/main/home/articles/Top5ArticlesDefault.js
  FE/src/component/main/home/institution/Inst.js
  FE/src/component/main/home/middle/Middle.js
  FE/src/component/main/kakaomap/KakaoMap.js
  FE/src/component/main/kakaomap/KakaoMapDefault.js
Labels: BE, FE, FIX, DESIGN

#58 [FIX] 프론트 에러 수정
  FE/public/logo.png
  FE/src/component/main/home/institution/Inst.js
  FE/src/component/main/kakaomap/KakaoMap.js
  FE/src/component/nav/Nav.js
Labels: FE, DESIGN

#57 [FIX] 채팅메시지 저장 API 수정
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatMessageApiController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatMessageStompController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatMessageDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseChatMessageDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatMessageService.java
Labels: BE, FIX

#66 [FIX] 카카오맵 렌더링 오류 수정
  FE/src/component/main/home/middle/Middle.js
  FE/src/component/main/kakaomap/KakaoMap.js
  FE/src/component/main/kakaomap/KakaoMapDefault.js
Labels: FE, FIX, DESIGN, REMOVE

#68 [FEAT] JWT Refresh Token 재발급 관련 컨트롤러 작성
  .gitignore
  BE/.gitignore
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/controller/ApiRefreshController.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  FE/.gitignore
Labels: BE, FEATURE

#69 [FEAT] Article, Category 도메인 연관관계 매핑
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/common/main/dto/MainArticleDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticlePostDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticleResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/ArticleCategory.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/repository/ArticleCategoryRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/article/repository/ArticleRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/category/controller/CategotyController.java
  BE/src/main/java/com/myapp/warmwave/domain/category/dto/CategoryAllPostDto.java
  BE/src/main/java/com/myapp/warmwave/domain/category/entity/Category.java
  BE/src/main/java/com/myapp/warmwave/domain/category/repository/CategoryRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/category/service/CategoryService.java
Labels: BE, FEATURE, REFACTOR

#73 [FEAT] Login/Logout view page 구현
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/component/hooks/useCustomLogin.js
  FE/src/component/nav/Nav.js
  FE/src/component/slices/loginSlice.js
  FE/src/component/user/kakaopost/KakaoPost.js
  FE/src/component/user/login.js
  FE/src/component/user/signin.js
  FE/src/component/user/signup.js
  FE/src/component/user/user.js
  FE/src/component/user/userApi.js
  FE/src/component/util/cookieUtil.js
  FE/src/component/util/jwtUtil.js
  FE/src/index.js
  FE/src/store.js
Labels: FEATURE, FE, FIX, REMOVE

#78 [FIX] Article 도메인 관련 PR 복구
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/ArticleCategory.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/resources/application.yml
  FE/src/App.js
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PostForm.css
  FE/src/component/article/post/PostForm.js
Labels: BE, FEATURE, FE, FIX

#81 [FEAT] 커뮤니티 게시글 BE + 리스트 페이지 FE
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/myapp/warmwave/WarmwaveApplication.java
  BE/src/main/java/com/myapp/warmwave/config/QuerydslConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/controller/CommentController.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/entity/Comment.java
  BE/src/main/java/com/myapp/warmwave/domain/community/controller/CommunityController.java
  BE/src/main/java/com/myapp/warmwave/domain/community/dto/CommunityListResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/community/dto/CommunityPatchDto.java
  BE/src/main/java/com/myapp/warmwave/domain/community/dto/CommunityPostDto.java
  BE/src/main/java/com/myapp/warmwave/domain/community/dto/CommunityResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/community/entity/Community.java
  BE/src/main/java/com/myapp/warmwave/domain/community/mapper/CommunityMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/community/mapper/CommunityMapperImpl.java
  BE/src/main/java/com/myapp/warmwave/domain/community/repository/CommunityListRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/community/repository/CommunityListRepositoryImpl.java
  BE/src/main/java/com/myapp/warmwave/domain/community/repository/CommunityRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/community/service/CommunityFacadeService.java
  BE/src/main/java/com/myapp/warmwave/domain/community/service/CommunityService.java
  BE/src/main/java/com/myapp/warmwave/domain/image/entity/Image.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Individual.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Institution.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/resources/application.yml
  FE/.gitignore
  FE/src/App.css
  FE/src/App.js
  FE/src/component/community/detail/CommunityDetails.js
  FE/src/component/community/detail/scripts.js
  FE/src/component/community/detail/styles.css
  FE/src/component/community/list/CommunityList.css
  FE/src/component/community/list/CommunityList.js
  FE/src/component/community/list/scripts.js
  FE/src/component/community/list/styles.css
Labels: BE, FE, DESIGN

#79 [Feat] 마이페이지 디자인 작업
  FE/src/App.js
  FE/src/component/user/mypage/editIndivInfo.js
  FE/src/component/user/mypage/editInstInfo.js
  FE/src/component/user/mypage/favoriteInstList.js
  FE/src/component/user/mypage/myArticleList.js
  FE/src/component/user/mypage/myChatRoom.js
  FE/src/component/user/mypage/myInfo.js
  FE/src/component/user/mypage/mypage.css
  FE/src/component/user/mypage/mypage.js
  FE/src/component/user/mypage/showIndivInfo.js
  FE/src/component/user/mypage/showInstInfo.js
Labels: FEATURE, FE, DESIGN, REFACTOR

#84 [FEAT] 회원가입페이지 디자인작업,유효성검사 추가
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/component/user/mypage/mypage.js
  FE/src/component/user/signup.js
  FE/src/component/util/jwtUtil.js
Labels: FEATURE, FE, FIX, DESIGN

#86 [TEST] service,controller 테스트코드 작성
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/address/service/AddressService.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatRoomController.java
  BE/src/main/java/com/myapp/warmwave/domain/email/entity/EmailAuth.java
  BE/src/main/java/com/myapp/warmwave/domain/email/service/EmailService.java
  BE/src/main/java/com/myapp/warmwave/domain/favorite_inst/controller/FavoriteInstController.java
  BE/src/main/java/com/myapp/warmwave/domain/favorite_inst/dto/ResponseFavoriteDto.java
  BE/src/main/java/com/myapp/warmwave/domain/favorite_inst/service/FavoriteInstService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestIndividualJoinDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestInstitutionJoinDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  BE/src/test/java/com/myapp/warmwave/domain/address/service/AddressServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/repository/ArticleRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatMessageControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatRoomControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatroomRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatMessageServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatRoomServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/controller/FavoriteInstControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/repository/FavoriteInstRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/service/FavoriteInstServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/controller/UserControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/repository/UserRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/service/UserServiceTest.java
Labels: BE, FIX, TEST

#87 [FEAT] 게시글 수정 및 삭제 로직 구현
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/common/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/repository/ArticleCategoryRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/image/repository/ImageRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  BE/src/main/resources/application.yml
Labels: BE, FEATURE, REFACTOR

#91 [TEST] 테스트코드 수정
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/myapp/warmwave/domain/address/repository/AddressRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/repository/ArticleRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatMessageControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatRoomControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatroomRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatRoomServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/controller/FavoriteInstControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/repository/FavoriteInstRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/service/FavoriteInstServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/controller/UserControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/repository/UserRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/service/UserServiceTest.java
  BE/src/test/resources/application.yml
  FE/package-lock.json
  FE/package.json
Labels: BE, TEST

#93 [REFACTOR] OAuth2 리팩토링
  BE/src/main/java/com/myapp/warmwave/config/oauth/CustomOAuth2User.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/CustomUserDetails.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/KakaoOAuth2UserInfo.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2Attributes.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2Provider.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuth2UserInfo.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/OAuthAttributes.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/SocialType.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/service/CustomOAuth2UserService.java
  BE/src/main/java/com/myapp/warmwave/config/oauth/service/CustomUserDetailsService.java
  BE/src/main/java/com/myapp/warmwave/domain/email/service/EmailService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/java/com/myapp/warmwave/domain/user/repository/UserRepository.java
  BE/src/main/resources/application.yml
  FE/src/component/nav/Nav.js
Labels: BE, REFACTOR

#94 [FEAT] Article, User 도메인 연관관계 매핑 적용
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/common/main/dto/MainArticleDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticlePostDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/ArticleCategory.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/ArticleType.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/category/controller/CategoryController.java
  BE/src/test/java/com/myapp/warmwave/domain/article/repository/ArticleRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatroomRepositoryTest.java
Labels: BE, FEATURE, REFACTOR

#104 [FIX] CORS 관련 리팩토링 및 버그 수정
  BE/src/main/java/com/myapp/warmwave/config/security/CorsConfig.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
Labels: BE, FIX, REFACTOR

#109 [REFACTOR] 이미지 저장 기능 및 게시글 CRUD 내부로직 개선
  BE/build.gradle
  BE/src/main/java/com/myapp/warmwave/config/security/AwsS3Config.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticlePatchDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PatchForm.js
Labels: BE, FE, REFACTOR

#116 [FEAT] 자동 배포 활성화
  BE/Dockerfile
  BE/build.gradle
  BE/settings.sh
  BE/src/main/java/com/myapp/warmwave/config/security/CorsConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/category/entity/Category.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/entity/ChatMessage.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/entity/ChatRoom.java
  BE/src/main/java/com/myapp/warmwave/domain/community/entity/Community.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Individual.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Institution.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/User.java
  BE/src/main/resources/application-secret.yml.default
  BE/src/main/resources/application.yml
  BE/src/test/java/com/myapp/warmwave/WarmwaveApplicationTests.java
  BE/src/test/java/com/myapp/warmwave/domain/article/repository/ArticleRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatroomRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/jwt/JwtTests.java
  BE/src/test/resources/application.yml
  FE/Dockerfile
  FE/nginx.conf
  FE/package.json
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PostForm.js
  FE/src/component/community/detail/CommunityDetails.js
  FE/src/component/community/list/CommunityList.js
  FE/src/component/main/home/NewArticle.js
  FE/src/component/main/home/middle/Middle.js
  FE/src/component/main/home/middle/MiddleBar.js
  FE/src/component/user/userApi.js
  FE/src/component/util/jwtUtil.js
  docker-compose.yml
Labels: BE, FE, FIX, REFACTOR, CI/CD

#119 [FIX & REFACTOR] CORS 관련 문제 해결
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtProvider.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/controller/ApiRefreshController.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/controller/JwtRefreshController.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/service/JwtRefreshService.java
  BE/src/main/java/com/myapp/warmwave/config/CorsConfig.java
  BE/src/main/java/com/myapp/warmwave/config/security/CookieManager.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/ResponseUserLoginDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
Labels: BE, FEATURE, FIX, REFACTOR

#121 Feature/#103
  FE/src/component/hooks/useCustomLogin.js
  FE/src/component/user/userApi.js
  FE/src/component/util/jwtUtil.js
Labels: FE, REFACTOR

#122 [COMMENT] 로컬 환경에서 테스트에 필요한 코드 주석 추가
  FE/.env.local
  FE/.env.production
  FE/src/component/slices/loginSlice.js
  FE/src/component/user/userApi.js
  FE/src/component/util/jwtUtil.js
Labels: FE

#126 [FEAT, REFACTOR] 게시글 CRUD 이미지관리 S3로 변경 및 내부로직 개선
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PatchForm.js
  FE/src/component/article/post/PostForm.js
Labels: BE, FEATURE, FE, REFACTOR

#128 Feature/#127
  .gitignore
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
Labels: BE, FEATURE

#129 [FEAT] 커뮤니티 댓글 작성, 수정, 삭제 버튼 + 기능
  BE/src/main/java/com/myapp/warmwave/config/AwsS3Config.java
  BE/src/main/java/com/myapp/warmwave/config/RedisCacheConfig.java
  BE/src/main/java/com/myapp/warmwave/config/RedisConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/controller/CommentController.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/dto/CommentResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/repository/CommentListRepositoryImpl.java
  FE/src/component/comment/Comment.js
  FE/src/component/comment/comment.css
Labels: FE

#132 [FEAT] 게시글 이미지등록 유효성검사, 작성자 IP 수집 기능 추가
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticlePatchDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticlePostDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
Labels: BE, FEATURE

#133 [FEAT] 게시글 상태변경 api 추가
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Status.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
Labels: BE, FEATURE

#137 [DOCS] API 명세서 일부 작성
  BE/build.gradle
  BE/src/docs/asciidoc/Category.adoc
  BE/src/docs/asciidoc/Chat.adoc
  BE/src/docs/asciidoc/FavoriteInst.adoc
  BE/src/docs/asciidoc/Main.adoc
  BE/src/docs/asciidoc/User.adoc
  BE/src/main/java/com/myapp/warmwave/domain/address/controller/AddressController.java
  BE/src/main/java/com/myapp/warmwave/domain/category/entity/Category.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/repository/CommentListRepositoryImpl.java
  BE/src/main/java/com/myapp/warmwave/domain/community/repository/CommunityListRepositoryImpl.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  BE/src/main/resources/application-secret.yml.default
  BE/src/test/java/com/myapp/warmwave/MainRestControllerTest.java
  BE/src/test/java/com/myapp/warmwave/TestConfig.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/category/controller/CategoryControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/category/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/category/service/CategoryServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatMessageControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatRoomControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/repository/ChatMessageRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/controller/FavoriteInstControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/controller/UserControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/service/UserServiceTest.java
Labels: BE, FIX, TEST, DOCS

#139 [Style] 소셜로그인용 이미지(구글,네이버,카카오 로그인)
  FE/src/assets/images/social/google.svg
  FE/src/assets/images/social/kakao.png
  FE/src/assets/images/social/naver.png
Labels: DESIGN

#140 [FEAT] SSL 인증서 추가
  FE/nginx.conf
  docker-compose.yml
Labels: CI/CD

#141 [FIX] FE 백엔드 API 호출 변경
  FE/src/component/user/signup&login/authApi.js
Labels: FE, FIX

#142 [FEAT] 게시글 단일 및 목록조회 시 작성자 주소 매핑기능 추가
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/dto/ArticleResponseDto.java
  BE/src/main/java/com/myapp/warmwave/domain/article/mapper/ArticleMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PatchForm.js
  FE/src/component/article/post/PostButton.js
  FE/src/component/article/post/PostForm.js
Labels: BE, FEATURE, FE, REFACTOR

#143 [FEAT, FIX] 채팅방 생성 API 연결 , 웹소켓 통신 USER 인증방식 변경
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/config/JwtHandshakeInterceptor.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/config/RmeSessionChannelInterceptor.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/config/WebSocketConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/config/WebsocketUserContext.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatMessageStompController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/controller/ChatRoomController.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatMessageDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseChatMessageDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseCreateChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/entity/ChatRoom.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatMessageService.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatRoomService.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatRoomControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatMessageServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatRoomServiceTest.java
  FE/src/App.js
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/chat/ChatMain.js
Labels: BUG, BE, FIX, TEST, REMOVE

#146 [FEAT] 커뮤니티 게시글, 댓글 기능 + 디자인 추가
  BE/src/main/java/com/myapp/warmwave/domain/comment/controller/CommentController.java
  BE/src/main/java/com/myapp/warmwave/domain/community/controller/CommunityController.java
  FE/src/component/comment/Comment.js
  FE/src/component/community/CommunityCategoryStyles.js
  FE/src/component/community/detail/CommunityDetails.js
  FE/src/component/community/list/CommunityList.js
  FE/src/component/community/write/CommunityUpdate.js
  FE/src/component/community/write/CommunityWrite.js
Labels: FE

#147 [FEAT] [BE}기관회원가입 시 사업자등록증 이미지 업로드 기능 추가 & [FE]일부수정
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/domain/image/entity/Image.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Institution.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/myapp/warmwave/domain/user/controller/UserControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/service/UserServiceTest.java
  FE/src/component/nav/Nav.js
  FE/src/component/user/daumPost.js
Labels: BE, FEATURE, FE, FIX, TEST

#149 [FEAT] [FE]기관회원가입 파일업로드 추가
  FE/src/component/hooks/useCustomLogin.js
  FE/src/component/user/signup&login/authApi.js
  FE/src/component/user/signup&login/individual_signup.js
  FE/src/component/user/signup&login/institution_signup.js
  FE/src/component/user/signup&login/login.js
Labels: FEATURE, FE

#150 [FEAT] 단일 게시글 내의 이미지 페이징 기능 추가
  BE/src/main/java/com/myapp/warmwave/domain/image/entity/Image.java
  BE/src/main/java/com/myapp/warmwave/domain/user/entity/Institution.java
  FE/package-lock.json
  FE/package.json
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PatchForm.js
  FE/src/component/article/post/PostButton.js
  FE/src/component/article/post/PostForm.js
Labels: FEATURE, FE

#152 [FIX] 프론트 api host 수정
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  FE/src/component/community/list/CommunityList.js
  FE/src/component/main/home/NewArticle.js
  FE/src/component/main/home/middle/Middle.js
  FE/src/component/main/home/middle/MiddleBar.js
Labels: FE, FIX

#157 [FIX] BE UserService 이메일링크인증 예외코드 수정, FE 쿠키,디자인 일부수정
  BE/src/main/java/com/myapp/warmwave/domain/email/service/EmailService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  FE/src/component/nav/Nav.js
  FE/src/component/slices/loginSlice.js
  FE/src/component/user/signup&login/login.js
Labels: BE, FE, DESIGN

#159 [FIX] 게시글 상태변화 버그픽스
  BE/src/main/java/com/myapp/warmwave/domain/article/entity/Article.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/image/service/ImageService.java
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
Labels: BE, FIX

#163 [FEAT] 프론트페이지 게시글 상태변화 반영
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  FE/src/component/article/detail/ArticleDetails.js
  FE/src/component/article/list/ArticleList.js
  FE/src/component/article/post/PostButton.js
Labels: FEATURE, FE, DESIGN

#165 [FEAT, FIX] 게시글 상태변화 API 채팅 연결
  BE/src/main/java/com/myapp/warmwave/common/exception/CustomExceptionCode.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/dto/ResponseChatRoomDto.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatMessageService.java
  BE/src/main/java/com/myapp/warmwave/domain/chat/service/ChatRoomService.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatRoomServiceTest.java
  FE/src/component/chat/ChatMain.js
Labels: BE, FE, FIX, REFACTOR

#164 [TEST] 테스트코드 작성
  BE/build.gradle
  BE/src/docs/asciidoc/Article.adoc
  BE/src/docs/asciidoc/Category.adoc
  BE/src/docs/asciidoc/Chat.adoc
  BE/src/docs/asciidoc/Comment.adoc
  BE/src/docs/asciidoc/Community.adoc
  BE/src/docs/asciidoc/FavoriteInst.adoc
  BE/src/docs/asciidoc/User.adoc
  BE/src/main/java/com/myapp/warmwave/domain/comment/controller/CommentController.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/mapper/CommentMapper.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/mapper/CommentMapperImpl.java
  BE/src/main/java/com/myapp/warmwave/domain/comment/service/CommentService.java
  BE/src/main/java/com/myapp/warmwave/domain/community/entity/Community.java
  BE/src/main/java/com/myapp/warmwave/domain/community/repository/CommunityRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/community/service/CommunityService.java
  BE/src/test/java/com/myapp/warmwave/WithMockCustomUser.java
  BE/src/test/java/com/myapp/warmwave/WithMockCustomUserSecurityContextFactory.java
  BE/src/test/java/com/myapp/warmwave/domain/article/controller/ArticleControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/repository/ArticleRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/article/service/ArticleServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/category/controller/CategoryControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatMessageControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/controller/ChatRoomControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatMessageServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/chat/service/ChatRoomServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/comment/controller/CommentControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/comment/repository/CommentRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/comment/service/CommentServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/community/controller/CommunityControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/community/repository/CommunityRepositoryTest.java
  BE/src/test/java/com/myapp/warmwave/domain/community/service/CommunityFacadeServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/community/service/CommunityServiceTest.java
  BE/src/test/java/com/myapp/warmwave/domain/favorite/controller/FavoriteInstControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/controller/UserControllerTest.java
  BE/src/test/java/com/myapp/warmwave/domain/user/repository/UserRepositoryTest.java
Labels: BE, TEST

#166 [FEAT] 마이페이지 기능 구현
  BE/src/main/java/com/myapp/warmwave/common/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/myapp/warmwave/common/jwt/JwtAuthFilter.java
  BE/src/main/java/com/myapp/warmwave/config/security/SecurityConfig.java
  BE/src/main/java/com/myapp/warmwave/domain/address/dto/AddressDto.java
  BE/src/main/java/com/myapp/warmwave/domain/address/service/AddressService.java
  BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
  BE/src/main/java/com/myapp/warmwave/domain/article/repository/ArticleRepository.java
  BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
  BE/src/main/java/com/myapp/warmwave/domain/user/controller/UserController.java
  BE/src/main/java/com/myapp/warmwave/domain/user/dto/RequestInstitutionUpdateDto.java
  BE/src/main/java/com/myapp/warmwave/domain/user/service/UserService.java
  FE/src/component/user/mypage/editIndivInfo.js
  FE/src/component/user/mypage/editInstInfo.js
  FE/src/component/user/mypage/favoriteInstList.js
  FE/src/component/user/mypage/myArticleList.js
  FE/src/component/user/mypage/myChatRoom.js
  FE/src/component/user/mypage/myInfo.js
  FE/src/component/user/mypage/mypage.js
  FE/src/component/user/mypage/passwordModal/changePasswordModal.js
  FE/src/component/user/mypage/passwordModal/checkPasswordModal.js
  FE/src/component/user/mypage/showIndivInfo.js
  FE/src/component/user/mypage/showInstInfo.js
  FE/src/component/user/signup&login/userApi.js
Labels: BUG, BE, FEATURE, FE, FIX, DESIGN, REFACTOR

#167 [FIX] FE 소셜로그인 연결
  FE/src/component/user/signup&login/individual_signup.js
  FE/src/component/user/signup&login/institution_signup.js
  FE/src/component/user/signup&login/login.js
  FE/src/component/user/signup&login/signup.js
Labels: FE, FIX

#170 fix: 이메일 링크 인증 경로 배포링크로 변경
  BE/src/main/java/com/myapp/warmwave/domain/email/service/EmailService.java
Labels: BE
